name: Format

on:
  workflow_run:
    workflows: ['Compile']
    types: [completed]

jobs:
  format:
    name: Check Formatting

    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Check Format
        run: echo 'Format check here'
